### ISSUE TITLE
Grant same read/write privileges to all users in group `users` 

### ISSUE THREAD

**Issue by gaow** [statgenetics/statgen-courses#4]
@cbroad I'm documenting what needs to be implemented. As discussed, by grant same read/write privileges to all users in group `users` it will solve the permission issue due to a bug in base-notebook image. But more importantly it will allow users to exchange data -- I'm sure there are advanced students in the group who are capable of helping others by copying their intermediate data-set to some folder for others to access. We should add it to `vm-setup`

**Comment by cbroad** [comment]
I think in a course situation most people would just download it and find a way to send it outside of our servers instead of sharing it to each other.  I would think that this mostly affects people who use login instead of launch that would like to download their data.

**Comment by gaow** [comment]
Okay another scenario is what if users have to / want to upload some files from their computer to the subfolders in work folder? Currently there will be permisison issues.

**Comment by gaow** [comment]
This problem has been resolved in `statgen-setup login` but not with `launch`

**Comment by gaow** [comment]
We have solved the problem by removing the problem itself ... currently we allow a user to run a server that works for mulliple exercises, instead of having each exercise beign a server that multiple users work on.
